### ISSUE TITLE
Drupal module

### ISSUE THREAD

**Issue by gazaston** [Wilto/Dynamic-Carousel#10]
I'd love to see this made up as a module for Drupal. LOVE IT.

**Comment by Wilto** [comment]
_Drupal._ We got history, Drupal and I. Bad blood.

…Let me see what’s involved in Drupal module-ing—mark this one down as a “maybe.”

**Comment by gazaston** [comment]
I know what you mean — she can be _nasty_ (and not in a good way). But lots of non-profits and good causes like it 'cos it's free and open-source, and surely those well-meaning folks deserve a little responsive slideshow loving?

;)

**Comment by jpamental** [comment]
I'm working on integrating it with a them now leveraging Semantic Views to tame the views output. Not sure about making a views plugin (likely beyond me) but I'll let you know how it works out this way at least!

Thanks - by the way - found this via Ethan Marcotte's Responsive Web Design book. Thanks - looks like a really nice bit of work!

**Comment by jpamental** [comment]
Well - guessing this isn't going to work in Drupal 6 - it's stuck at jQuery 1.3.2 (jQuery UI 1.6). Been wrestling with this for a while now and just realized that's likely why it's not working.

Bummed - wonder if it's possible to do this with 1.3.2? I've had pretty good luck developing a responsive them with fluid images otherwise.

**Comment by Wilto** [comment]
Oh, weird timing. I was running it on an old version of jQuery yesterday out of curiosity, and it was okay. As soon as I have a chance I'll give it a shot with 1.3.2 and see if I can't get it sorted.

**Comment by jpamental** [comment]
That would be absolutely stellar! I've tried many ways to do this otherwise with other 'standard' Drupal slideshow methods and it's unpredictable to say the least. It would be amazing to get this working there.

Sidenote: adding the data-autorotate to the middle example in your demo doesn't seem to work (the one with the 5 dots below rather than prev/next) I'm hoping to use that style with images on the site I'm working with now.

Cheers,

Jason

**Comment by Wilto** [comment]
Ah, yeah, good call--right now, the autorotate just triggers a click on the next/prev nav links. Now that everything is event-driven I can fix that up.

**Comment by jpamental** [comment]
No worries on the autorotate - glad to help test/debug whatever I can. Biggest win would be to get this working in jQ 1.3.2. (would be using this on 5-7 sites this month for schools that I'm working on - all with a responsive base theme!)

Thanks again - let me know what I can do to help!

Jason

**Comment by jpamental** [comment]
By the way - tested your demo back to jQuery 1.4.0 and it worked great - just wish there were fewer hoops to jump through to get 1.4.x working in Drupal 6!

**Comment by Wilto** [comment]
Alright, I think we are officially fixed for 1.3.2. Give the latest a shot, yeah?

**Comment by jpamental** [comment]
SWEET!!!

http://sas.sandbox.schoolyard.com/

The three images are pulled by a 'view' (and using the Semantic Views module I can structure the markup to mimic what you use pretty much). Working great in FF, Safari and Chrome, resizing away. Last bit of flash money would be to get the auto-advance working, but I'm REALLY excited and grateful for what you've done today!

THANK YOU!

Jason

**Comment by jpamental** [comment]
More details:

Works perfectly in Safari, FF and Chrome on my Mac w/ 10.7, also on my iPad and iPhone (resizing on rotation perfectly)

IE9 in Win7 is perfect

IE8 is good w/square dots

IE7 - 3 images exposed sticking out to the right (end-to-end)

Figuring that if there's no clear fix then I can use my 'less than IE8' CSS to simply hide the overflow and show a single static image.

Just fantastic. Thank you!

How can I help or support development?

Jason

**Comment by Wilto** [comment]
That IE7 issue sounds pretty easily fixable. Got some IE troubleshooting slated for this weekend—I’ll keep you posted.

**Comment by Wilto** [comment]
Hey, have a look at the latest push: I sorted out some other IE 6/7/8 issues, and it may fix the above. Otherwise, it sounds like it could be an unrelated CSS thing—you might have to manually tack an `overflow: hidden;` onto the carousel’s parent container.
