### ISSUE TITLE
Bug in IE6

### ISSUE THREAD

**Issue by jphalip** [Wilto/Dynamic-Carousel#11]
The sliders #2 and #3 on the demo page at http://matmarquis.com/carousel/ do not work properly on IE6. Two slides are shown at the time. I'm not sure if it's an issue with the CSS or the JS.

**Comment by Wilto** [comment]
And lo, there did one bug did beget many—as is IE6’s wont.

Annnd fixed. Thanks for the heads-up!

**Comment by jphalip** [comment]
Woah, awesome! That was fast, man. Thank you ;)

By the way, could you add the license at the top of the JS file?
