### ISSUE TITLE
Slides containing links don't appear correctly when focused on with the tab key

### ISSUE THREAD

**Issue by jphalip** [Wilto/Dynamic-Carousel#12]
As an accessibility measure, people who can't use a mouse may jump from link to link by pressing the tab key. If one reaches a link from inside a slide, the slide becomes visible but it isn't correctly aligned left, and so you can see some part of the preceding slide. It'd be awesome if the on-focus slide occupied the entire slider viewport, like when using the regular previous/next buttons.

**Comment by Wilto** [comment]
Good call. This thing is slated for a major a11y overhaul very soon—thanks!

**Comment by Wilto** [comment]
ARIA’d from top to bottom, including the new optional pagination tabs. Keyboard support is enabled when focus is on either the next/prev links or the tabs, and the slides themselves are now set up in such a way that keyboard navigation and screen readers should treat them as part of the flow of the surrounding page. Have a look at http://wilto.github.com/Dynamic-Carousel/ and let me know what you think!

**Comment by Wilto** [comment]
This issue specifically has been addressed, and the fix has been rolled into the master branch. Still needs some work from an a11y standpoint, but it’s getting there.
