### ISSUE TITLE
IE 7 Error

### ISSUE THREAD

**Issue by sdelamo** [Wilto/Dynamic-Carousel#13]
By clicking in the next button in http://responsivewebdesign.com/robot I get the next message:

Line: 19
Error: Unable to get value of the property 'match': object is null or undefined

**Comment by Wilto** [comment]
Ugh, sorry man—I know exactly what that is. Rest assured: a fix is on the way!

**Comment by sdelamo** [comment]
thank you

**Comment by Wilto** [comment]
This issue should now be resolved—have a look at http://wilto.github.com/Dynamic-Carousel/ and let me know if you’re still seeing that error. Thanks for the bug report!
