### ISSUE TITLE
Request: Auto Transition

### ISSUE THREAD

**Issue by rowanflack** [Wilto/Dynamic-Carousel#14]
Absolutely fantastic carousel, one of the few to take responsiveness into the equation. 

Feature request: Would love to see an "auto-advance" slide added into this carousel.

**Comment by rickydazla** [comment]
2nd!

**Comment by Wilto** [comment]
What do you guys think of using a data- attribute on the carousel wrapper, so this can be more easily applied on a case-by-case basis? I’m envisioning something like `<div class="slidewrap" data-autorotate="1000">`, where data-autorotate contains the rotation speed.

**Comment by rowanflack** [comment]
I think that'd be a great idea, nice and simple to control! Looking forward to the release. Really appreciate the support.

**Comment by rickydazla** [comment]
A data attribute would work really well for me. I will be implementing this on some Shopify sites and will be able to integrate this with their liquid code so that clients can control speed from their settings panel.

Loving your work!

**Comment by dfischer** [comment]
+1

Please add this. I love the html5 data-attribute idea.

**Comment by Wilto** [comment]
Somebody start the drumroll.

**Comment by jamesdoc** [comment]
_drumroll_

**Comment by Wilto** [comment]
Done. Have a look at the demo page.

I made a note of this in the readme, but just to reiterate: right now, the auto-advance is dependent on the carousel in question having next/prev links. This thing has reached the point where it really needs to be event-driven (so instead of jumping between functions, a “moveLeft” event is fired on the carousel itself, triggering further actions), so that’s the plan—rather than triggering a click on the next/prev controls, the timeout will trigger a “move” event.

That’s next up on the list, but probably won’t be in place until early next week.

**Comment by rickydazla** [comment]
WTF is all that noise about?! Who brought drums? Oh... hold on... NIICE1!

**Comment by dfischer** [comment]
You rock @wilto! Thanks!

**Comment by dfischer** [comment]
I just want to say that I love that you're taking full advantage of latest
HTML5 standards. Thank you.

**Comment by boberetezeke** [comment]
The auto transition works great....in Chrome. In Chrome it goes back and forth successfully. In Firefox 4 and Safari it just goes to the right and stops. Looking at the code it seems that in the function autoAdvance it gets the current left margin and assumes that it is in percentages. On Firefox and Safari it is in pixels, so the calculation gets it wrong. There are ways to fix this but I don't know of a way to get the value back in percentages if it is given in pixels. It could be manually converted to percentages if the divided by the slide width.

Any help would be appreciated.

**Comment by Wilto** [comment]
Annnd I’m an idiot. Fix forthcoming.

**Comment by boberetezeke** [comment]
Wow thanks!

**Comment by Wilto** [comment]
Fixed. 

Completely my bad. I thought this fix had made it into the recent big commit. Applied and retested in the all of the above (including IE 6/7—and if you can make it there, you can make it anywhere).

**Comment by dfischer** [comment]
Thanks for trying to make it compatible in IE6. I think you can save
yourself some headache and ignore it in the future. If Google does, so can
you!

**Comment by Wilto** [comment]
Hey, this gig wouldn’t be any fun if it were easy, right?

But no worries: there’s no real hackery going on for the sake of clunky old IE—and I’m sure as hell not gonna fix anything to the detriment of any of the grown-up browsers.
