### ISSUE TITLE
License

### ISSUE THREAD

**Issue by allmarkedup** [Wilto/Dynamic-Carousel#15]
Hey mate, just wondering if you could add a license declaration somewhere so people know what they can/can't do with your code, what projects they can use it in etc. Would be much appreciated!

Cheers,

Mark

**Comment by Wilto** [comment]
Done. MIT license, for want of a DLAYWWTBTMIYDACPL (Do Literally Anything You Want With This, But Tell Me If You Do Anything Cool Public License).

**Comment by allmarkedup** [comment]
Perfect, thanks mate, and will do :-)
