### ISSUE TITLE
Webkit Mobile offset issue

### ISSUE THREAD

**Issue by dirtystylus** [Wilto/Dynamic-Carousel#20]
Hi and thanks for making this plugin - I heard about it via @beep's RWD book, and I've been using it in a few projects since. I've run into a bit of a weird issue, and only on the mobile webkit browsers that I've used for testing (Safari on iOS 4.3.5, stock browser on Android 2.2). On slideshows of a certain length the offset seems to shove the images too far to the left. That is, you can see a bit of the next image start to peek out. This offset seems to increase the further into the images you go, so that by the end of the slideshow you've got a noticeable column peeking out on the right side of the current image. Now, there doesn't seem to be a pattern as far as I could discern. Here's four test links I set up:

[5 images, no issues](http://ryan.160over90.com/carousel-5.html)
[11 images, offset issue](http://ryan.160over90.com/carousel-11.html)
[15 images, offset issue](http://ryan.160over90.com/carousel-15.html)
[16 images, no issues](http://ryan.160over90.com/carousel-16.html)

All the images are the same size (1024x486). Again, the issue doesn't seem to show up on desktop browsers, only on the two webkit mobile browsers that I've been testing against.

**Comment by Wilto** [comment]
Now _this_ is how one logs an issue! 

I have heard tell of this WebKit rounding bug, and those test cases will be hugely helpful in tracking it down. I’m refining a lot of things over the next few days, and one change in particular may just fix this issue—but if not, I definitely have a patch in mind. Thanks!

**Comment by Wilto** [comment]
Closed and immediately reopened because I am not good at using a computer.

**Comment by Wilto** [comment]
Sorry for the wait—I think I’ve got this resolved. Have a look at the latest, and let me know if it helps!

**Comment by dirtystylus** [comment]
Mat, the latest download (b6a48f3) from the tar/zip didn't seem to work, period - the demo doesn't, and dropping in the plugin.js file into my project results in a slideshow that I can't advance. No JS errors, though, so it's a bit of a head-scratcher.

**Comment by Wilto** [comment]
Argh, git snafu. Have a look at the latest—really sorry about that!

**Comment by dirtystylus** [comment]
Weird. I'm still getting the same behavior, whether I use the binary downloads or clone the project from git. Testing in Safari 5.1 and Chrome (13.0.732.220), and an iPad with 4.3.5.

**Comment by dirtystylus** [comment]
Mat, so: offset issue appears to be gone with the latest revision, thanks for fixing that. I'm going to open a separate issue for a break in the pagination functionality.
