### ISSUE TITLE
addNav controls not working in IE7+error warning

### ISSUE THREAD

**Issue by chillfinn** [Wilto/Dynamic-Carousel#21]
The generated nav controls for prev/next don't seem to work in IE7

Also I'm getting an error message stating: 'moveTo' is null or not an object on line 245

Yeh IE7 sucks but...

**Comment by Wilto** [comment]
But, no reason we shouldn’t be able to make it work anyway, yeah? I spent some time looking into this today, and it seems like a weird one—a fix is in the works, though.

**Comment by chillfinn** [comment]
Yeh, we gotta cover all bases as pro's :D Otherwise you've done a brilliant job there, thanks!

**Comment by Wilto** [comment]
That was, in fact, a weird one—I didn’t realize that the “move” event was overlapping an event built into jQuery’s `animate()` functionality, and that overlap was firing the event a bunch of times. Turned up an unrelated issue in the `navState` function and fixed that as well. Looks like we’re back to 100% in 6/7/8.

**Comment by chillfinn** [comment]
I'm still getting the same issue - is that committed to the download?
