### ISSUE TITLE
data-autorotate

### ISSUE THREAD

**Issue by jpamental** [Wilto/Dynamic-Carousel#22]
Hey Matt - any chance you might have a quick fix for data-autorotate when using the pagination=true/addNav=false (little dots)

Launching the site I've been working on with your plugin in Drupal this afternoon and it would be nice to get that bit sorted if at all possible.

Thanks again - 

Jason

**Comment by Wilto** [comment]
Should be squared in the latest version—sorry, should’ve sent you a heads-up!

**Comment by jpamental** [comment]
Awesome - thanks! Question - is it possible to call that from the script where you pass in 'autoNav: true' etc, or only from the HTML? Just curious...

**Comment by Wilto** [comment]
The data- attribute only, for the time being—seemed to make the most sense, in terms of keeping such things granular.

**Comment by jpamental** [comment]
Got it. Ironically, it's far easier for me to put it in the JS file than modify the 'view' output in Drupal! Not impossible by any stretch - just more separate view files. It'd be cool to figure out a way to modularize it, but my brain isn't up for that yet.
