### ISSUE TITLE
'Slidewrap' name and swiping

### ISSUE THREAD

**Issue by ghost** [Wilto/Dynamic-Carousel#24]
I noticed in the demo that only the first example slides would advance via a swipe. After messing with it a bit, I saw that in the initializing script if there's a number after '.slidewrap' the slider wouldn't swipe: e.g. '.slidewrap2' and '.slidewrap3' won't advance with a swipe. Taking the number out makes swiping work.

**Comment by Wilto** [comment]
Oof, not cool—that’s a regression, for sure. I’ll look into it over the weekend. Thanks!

**Comment by Wilto** [comment]
Patched and pushed. The dragSnap event was a little too specific in what elements get dragged and/or snapped. Thanks for the heads-up!

**Comment by Wilto** [comment]
Introduced a couple of bugs with that one—take two coming soon.

**Comment by Wilto** [comment]
There we go.
