### ISSUE TITLE
Speed oddness (granted, in Drupal w/jQuery 1.3.2)

### ISSUE THREAD

**Issue by jpamental** [Wilto/Dynamic-Carousel#25]
Speed of transition seems uneven and not sure how better to describe: set for 800, 3 images in rotation: first has the 'right' delay, next one might be very fast, another might be OK. You can view it in action here:

http://www.standrewsch.org

Thanks for all the work - really appreciate it. Hope we can smooth this out - let me know how I can help.

Jason

**Comment by Wilto** [comment]
Have a look-see at the most recent push—this should now be resolved.
