### ISSUE TITLE
Pagination triggering namespace

### ISSUE THREAD

**Issue by paulmist** [Wilto/Dynamic-Carousel#30]
Howdy,

I've switched on pagination which is great (although I'm looking to define where it should be generated) and noticed that the links aren't aware when they are selected, and are still running the 'beforemove' namespace.

How might I stop this firing?

Cheers

**Comment by paulmist** [comment]
OK. Think I've sorted this myself, however, I'm not sure if this would be the best way to do it or not?

I changed the following in the $pagination function.

``` jquery
.find('a').click( function(e) {                         
    var current = $(this).parent().index(),
    move = -( 100 * ( current ) ),
    $slider = $oEl.find( opt.slider );
    if($(this).parent().attr('class') == opt.namespace + '-active-tab'){
        return false;
    } else {
        $slider.trigger( "move", { moveTo: move });
    }
    e.preventDefault();
});
```

**Comment by Wilto** [comment]
Just pushed a very similar fix: I’m checking against the `aria-active` attribute on the link itself—to save us a little bit fo DOM traversal—and established the variables after said check so we’re not running any unnecessary code.

**Comment by paulmist** [comment]
Great! I'll check it out. Thanks
