### ISSUE TITLE
'moveTo' is null or not an object (IE)

### ISSUE THREAD

**Issue by richardwiggins** [Wilto/Dynamic-Carousel#31]
Hi Matt,

Sorry to be a pain, but in IE8 (haven't tested other IE versions yet) when I click to navigate through the slides, IE throws up a JS error (below). Any ideas?

Message: 'moveTo' is null or not an object
Line: 231
Char: 5
Code: 0

Cheers, Richard

**Comment by Wilto** [comment]
No worries, man! This has, I believe, been patched-up. I was using `move` as the event name, which it turns out is used by jQuery’s animate method—meaning IE was firing the `move` event multiple times, without a `moveTo` value. Have a look at the latest and let me know if we’re good to go!

**Comment by richardwiggins** [comment]
Howdy, I thought I was already running the latest JS but just downloaded to to make sure. Unfortunately it's still there.

**Comment by Wilto** [comment]
You might have to give your cache a clear—IE can be really stubborn about that.

**Comment by richardwiggins** [comment]
Nope, it's still there unfortunately. Tried on a different machine to make sure.

**Comment by Wilto** [comment]
Shenanigans. Alright sir, had to be sure—I’ll check it out ASAP!

**Comment by richardwiggins** [comment]
No problemo and no rush from my pov, this site is a very very long way off from going live.

**Comment by Wilto** [comment]
`if( moveTo == null || otherwiseNotFixed ) {
hat.eat();
}`

Have a look at the latest on master, and we should be good to go.
