### ISSUE TITLE
addNav controls not working in IE7+error warning

### ISSUE THREAD

**Issue by chillfinn** [Wilto/Dynamic-Carousel#33]
Hi, sorry if I've missed something, but I still don't think this plugin works in IE7 with the generated prev/next links, and I'm getting the js errors :(

**Comment by Wilto** [comment]
Sorry! This thing kind of fell into disrepair for a little bit, while I was flat-out working on a (very exciting and responsive) project. I’ve just pushed a few things, and I’m confident that the IE issues will be resolved now.
