### ISSUE TITLE
Multiple carousels, single nav buttons

### ISSUE THREAD

**Issue by paulmist** [Wilto/Dynamic-Carousel#34]
Hi

I've got multiple carousels that I'd like to control using the same links (.next, .prev).

Anyway I can achieve this easily?

Thanks

**Comment by paulmist** [comment]
Have worked this out for prev/next buttons - just use a trigger('click') and leave the secondary carousel links empty. An odd way to do it, but it works. Can't do the same with pagination though. Any thoughts on a better way to do this?

Thanks

**Comment by Wilto** [comment]
You should be able to target multiple sliders based on the `href` of the next/prev links. You’d just point them at the id of the slider in question. I just gave it a shot in my local repo, and it seems to have done the trick.

**Comment by paulmist** [comment]
So you'd basically drop in multiple hrefs with differing IDs as the value?

I ended up using the gist you advised and the carousel script with a trigger() activating the former from the links of the latter

**Comment by Wilto** [comment]
Ah, yeah, that gist for setting up a fading slider? `trigger()` is the way to go using that one, for sure.

**Comment by paulmist** [comment]
Yeah works a treat, especially since my second "carousel" really works as overlaid, crossfaded content.
