### ISSUE TITLE
New master release not working

### ISSUE THREAD

**Issue by richardwiggins** [Wilto/Dynamic-Carousel#35]
Hi Matt,

I've just downloaded the new master (ala Sep 10) and it doesn't appear to be working at all.

I dropped the JS straight into my dev and couldn't get it working. After much head scratching (I don't have dandruff!) I thought I'd better take a look at your demo again and that doesn't appear to be working either. Can't actually navigate through any of the slides.

Any ideas?

P.S. Congrats on the re-launch of The Boston Globe. It looks great and can't wait to delve a bit deeper. Good work!

Richard

**Comment by Wilto** [comment]
Truly, I am the worst—just a git hiccup, my bad. Should be alright now!

Also: thanks! There are a few things that could stand work here and there, but all in all it’s looking really great. A genuine honor to work on.

**Comment by richardwiggins** [comment]
Um, sorry bud.... just downloaded your update but it's still not working. I'm literally just trying your demo file at the moment.

**Comment by Wilto** [comment]
Okay, bizarre. Working fine here (across all the modern browsers, at least). Maybe clear caches, just in case? Anything weird popping up in the console?

**Comment by richardwiggins** [comment]
This is bizarre. Cleared caches and tried it in Safari, Chrome and FF. No errors popping up in the console.

One thing that does seem a little odd, is the files (in download from GitHub) are being shown as updated at 08.37. My local time is 17.13. Does that make sense to you?

**Comment by fschroiff** [comment]
Hi, I have a similar issue. The pagination links in the demo file do not work at all. Prev/next links work fine.
I'm on Mac OS 10.6.8 newest versions of Chrome & Safari.
