### ISSUE TITLE
slideHed links not changing slides

### ISSUE THREAD

**Issue by boberetezeke** [Wilto/Dynamic-Carousel#40]
Clicking on the generated links don't change the slides. I think I have a fix for it on my fork (boberetezeke/Dynamic-Carosel). Without my change on the demo.html the First Slide, Second Slide, etc links do nothing. Not sure if this used to work or what. Also not sure how to submit changes to a forked project (I have never done this before).

Thanks for your work,
Steve Tuckner

**Comment by Wilto** [comment]
Ah man, good catch! Looks like that change fixes the issue.

If you open up your branch in the web interface, you should have a “pull request” button towards the upper-right. Hit that button and it will send the commit over to me. Give it a shot—they make it near-impossible to break anything.
