### ISSUE TITLE
creating multiple carousels on one page

### ISSUE THREAD

**Issue by ajlohman** [Wilto/Dynamic-Carousel#43]
I'm creating multiple sliders on a page and running into problems in Chrome.  All sliders except the last one skip forward 2 slides.  The last slider on the page works fine.  Anyone no why this is happening?

Here's the example:
http://andrewlohman.com/work/

First 2 sliders skip forward.  The last one works great.

**Comment by Wilto** [comment]
Hey, sorry, just got a chance to look into this—are you still seeing this issue? I can’t seem to recreate it on the link above.

**Comment by Wilto** [comment]
Ah, okay, looks like you swapped out my script for another one.

**Comment by ajlohman** [comment]
Hey, thanks for the quick response.  I couldn't figure out why it was not
working and in a last ditch effort I tried a different carousel and it
worked.

Thanks again!
