### ISSUE TITLE
Continuous Cycle?

### ISSUE THREAD

**Issue by jonpond** [Wilto/Dynamic-Carousel#45]
As you click through each one, is there a way to enable it to cycle back around to the first one?

**Comment by Wilto** [comment]
Hey @jonpond,

This is pretty tricky the way things are set up right now, but I have a feeling that it will be a lot easier once I finish moving over to transform-based animations rather than the current `margin-left` shenanigans. No simple way of doing this at the moment, but it’s in the works!

**Comment by jonpond** [comment]
Sounds good, thanks!

**Comment by markadrake** [comment]
I haven't noticed any changes made to enable this.

If my client decides to go with this fluid-width slider in lieu of the nivo-slider, I'll probably be making some edits to enable continuous next or prev movement. I'll post back here to let you know :)

**Comment by kylamedina** [comment]
No way to do this yet? Looping would make this awesome.

**Comment by mikeebee** [comment]
Plus 1 for looping! My carousel has sequencial instructions so it makes no sense at the moment! : )

**Comment by markadrake** [comment]
Well I noticed that the current script does loop, but it starts cycling backwards instead of starting at 0 (or slide 1) again. I'll take a look at this and see if there's a quick fix for you guys who want it to restart at 0.

**Comment by fourroses666** [comment]
+1 for looping :) 

Really really nice script, damn it like it so much. +1

**Comment by MaryLiz** [comment]
Would also be very interested in looping, as all of my clients request it. Let me know if this feature is ever added. Thanks!
