### ISSUE TITLE
Mo’ Better Swiping

### ISSUE THREAD

**Issue by Wilto** [Wilto/Dynamic-Carousel#5]
The subject pretty much says it all.

**Comment by ghost** [comment]
Swiping is pretty clunky right now. Is there a way to smooth out a bit?

**Comment by Wilto** [comment]
Hah, you should’ve seen it before. I’ve opened a new issue for this one, with some details: https://github.com/Wilto/Dynamic-Carousel/issues/23

You can just throw a “+1” in there so you’re notified if I update the issue.
