### ISSUE TITLE
Pagination Feature request

### ISSUE THREAD

**Issue by since1976** [Wilto/Dynamic-Carousel#6]
Love this plugin so much, thanks for releasing it.
Wondering if you've thought about adding a pagination/paging feature? This is a pretty common pattern these days and would certainly enhance user experience and make this plugin more awesomer than it already is.

Cheers
Dan

**Comment by Wilto** [comment]
Yeah, totally doable. I’ve had a couple of requests for a paginated variant—I’ll have something posted soon.

**Comment by chrism** [comment]
Would love this feature too... great plugin!

**Comment by Wilto** [comment]
Have a look-see at this, folks:
http://wilto.github.com/Dynamic-Carousel/

Note that there’s some sweet keyboard support in play, and it’s all been slathered in some rich accessibility sauce. Let me know what you think, yeah?

**Comment by rickydazla** [comment]
Love it. Pagination would make it dominate.

**Comment by Wilto** [comment]
Sorry, the link from June 26th is now defunct. I have this pretty much finished—just a few more tweaks needed before I roll this into the master branch. Look for it over the weekend.

**Comment by projectscribe** [comment]
Great plugin!  Looking forward to pagination also if you are working on this...

**Comment by projectscribe** [comment]
Guess I should have read the readme...nice.  Great stuff!

**Comment by chrism** [comment]
only just had chance to pull down the latest version... LOVE THIS.

amazing work wilto, much appreciated.

**Comment by Wilto** [comment]
Thanks, guys. Glad to see people usin’ it!
