### ISSUE TITLE
This code doesn’t not suck.

### ISSUE THREAD

**Issue by Wilto** [Wilto/Dynamic-Carousel#61]
Ah, the responsive carousel plugin. I was so young, back when I wrote this—so naïve. A wide-eyed developer, just starting to make his way in the world. One whole year ago.

I’m rewriting this. Stay tuned.

**Comment by davidrivers** [comment]
What's so not unsucky about your code? Do you have a new version yet?

**Comment by Wilto** [comment]
Absolutely: https://github.com/filamentgroup/responsive-carousel

Nothing glaringly wrong with this repo, but the link above—that’s the new hotness.
