### ISSUE TITLE
Swiping on the first slide

### ISSUE THREAD

**Issue by matthewcrist** [Wilto/Dynamic-Carousel#7]
Trying to swipe to the previous slide on the first slide gets stuck. Occasionally it will  go to the second slide. I was only able to reproduce this on the second carousel on http://wilto.github.com/Dynamic-Carousel/.

Screenshot: http://cri.st/7UmW

**Comment by Wilto** [comment]
Good catch—thanks for filing this!

**Comment by Wilto** [comment]
Hey Matt,

Any chance you’re still seeing this? There have been some improvements to the dragSnap event, and I’m having trouble reproducing it—hoping it got fixed somewhere down the line.

**Comment by matthewcrist** [comment]
It's working perfectly now.
