### ISSUE TITLE
auto slide on iphone

### ISSUE THREAD

**Issue by fourroses666** [Wilto/Dynamic-Carousel#70]
I love this light weight script!

On my mobile (iphone) it is auto sliding when i'm not touching anything, on a browser it's not auto sliding.
I'd like to set it off for mobile. How can i do this?

**Comment by mathiasbynens** [comment]
Could you provide a test case to reproduce the issue?

**Comment by fourroses666** [comment]
I removed the: data-autorotate="5000" and it's fixed.

**Comment by fourroses666** [comment]
double post*
