### ISSUE TITLE
Disabled pinch/zoom on iOS?

### ISSUE THREAD

**Issue by beep** [Wilto/Dynamic-Carousel#9]
I’m not sure, but I think the carousel plugin might be a little greedy with capturing touch/swipe events. To replicate the bug I’m seeing:
1. Hold an iPad in portrait mode.
2. Open http://responsivewebdesign.com/robot/
3. After the page has loaded, rotate the iPad into landscape mode. This’ll trigger iOS’s lovely zooming bug on `width=device-width` viewport settings. (Yay.)
4. Try to pinch to zoom out. You won’t be able to. It sucks. You might cry a little.

You can, however, double-tap to zoom out.

I noticed this on the iPad, but it might affect other iOS devices as well. (The sample page disables the plugin below a certain resolution threshold.)

**Comment by Wilto** [comment]
Fixed, pushed, etc., and I didn’t even cry.

…Okay I cried a little yes.

**Comment by beep** [comment]
Your tears sustain me. And fixed this issue. What.

(Amazing work, sir! Thanks so much.)
